### PR TITLE
Added the inspect script

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
With `npm run inspect` command, now you can inspect your code directly using the Chrome Dev Tool with Nodemon's hot reload! 🎉

For more info: https://nodejs.org/en/docs/guides/debugging-getting-started/

### CODE REVIEW

**Comment by bradtaniguchi** [comment]
Should this command be different then the normal `dev` command? Have you seen any issues with always running the debugger?

Also adding that doc link and reference on using this command to the README would help :)

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi  You want to merge this command with the `dev` command?

**Comment by Twaha-Rahman** [comment]
Haven't you used the `node --inspect index.js` command before? It's exactly that command only with Nodemon...

**Comment by bradtaniguchi** [comment]
> Haven't you used the `node --inspect index.js` command before? It's exactly that command only with Nodemon...

I've used inspect for ts-node/node/nodemon, and most of the time its just on the "`dev`" command. The only times I've seen there be issues is if you start running multiple "inspect" processes on the same port, then some processes wont start (shouldn't happen to this bot).
Along with that the process of connecting to the inspect differs depending on the situation, like I've had to setup some settings in VSCode to get one of my projects working. 

I was mainly asking if you've seen any issues/roadblocks that we should pay attention to here.

**Comment by Twaha-Rahman** [comment]
No....just running the command and  opening `chrome://inspect/` shows me the instance....

Capture

From there, I can click `Inspect` and start debugging....

Haven't run into any problem so far....

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi I have to ask out of curiosity, have you used `ndb` before?

**Comment by bradtaniguchi** [comment]
Never heard of `ndb` before.

And cool easier then what I've experienced haha, move the `--inspect` flag to the `dev` script and remove the `inspect` script and it should be good.

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi Done!

**Review by bradtaniguchi — APPROVED** [review]

**Pull request merged**
