### PR TITLE
Add welcome/depart messages

### PR DESCRIPTION
**Pull request by naomi-lgbt**
Did some research on how to write this - I assume it goes in the same file where message commands are read?

Might need to be tested -  I don't have the bot set up locally yet.

### CODE REVIEW

**Comment by bradtaniguchi** [comment]
> Might need to be tested - I don't have the bot set up locally yet.

Yea it would be preferred to get it working first locally to test it. Need to add some info on at least where to get this information.

**Comment by naomi-lgbt** [comment]
I'll fiddle around and see if I can get the bot set up locally and report back.

**Comment by naomi-lgbt** [comment]
image

Local testing discovered incorrect syntax with initial commit. Discord.js documentation demonstrated a method for sending a welcome message to a specific channel - in my case, "introduction". We can change the target channel if we want.

**Comment by naomi-lgbt** [comment]
https://discord.js.org/#/docs/main/stable/examples/greeting

**Comment by bradtaniguchi** [comment]
Thinking about the original gitter bot, it never had a welcome system like this as Quincy said it would spam to the channel to much.

This bot should be able to **message a person directly after they have joined**, and have a formatted message (so we can link stuff, like the freeCodeCamp code of conduct).

As such, I **dont** think we want this feature right now. Its good for experimenting, but this bot will at least only have features that could potentially go into the future "official" bot.

**Comment by naomi-lgbt** [comment]
image
Direct welcome message tested, appears functional.

**Comment by Ryuno-Ki** [comment]
Could you try adding some Markdown? Like a link or italic?

**Comment by naomi-lgbt** [comment]
New welcome message, with a link and an emoji for @Ryuno-Ki 😄 
Also added the `help` requirement to match this file to #15

**Review by bradtaniguchi — APPROVED** [review]
Looks good to me!

**edit** just noticed this has an announcement message logic. I don't think we need/want this in the FCC version of this bot, but I'll accept it for now because
1. I already said LGTM haha
2. We might want to perform "teardown" logic of any account connection between the user's discord account and FCC in the future.
3. This bot can spam a bit, no biggie.

**Pull request merged**
