### PR TITLE
Add test support using Jest

### PR DESCRIPTION
**Pull request by Twaha-Rahman**
Added Jest with additional configurations for testing

### CODE REVIEW

**Comment by Twaha-Rahman** [comment]
This PR will close #6 and is related to #36

**Review by bradtaniguchi — COMMENTED** [review]
Setup looks fine at a glance, can you also add a `test` step to the `.travis.yml` to run jest?

**Comment by Twaha-Rahman** [comment]
@bradtaniguchi Working on it...

**Comment by Twaha-Rahman** [comment]
Added `test` step to `.travis.yml`! 😃

**Review by bradtaniguchi — APPROVED** [review]
LGTM 👍 🚀 :shipit:

**Pull request merged**
